### ISSUE TITLE
Images in articles not displaying in Article Reader in Voyager Story

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-concierge#4] opened 2019-12-06 17:09 UTC
### Issue:
Images in Articles not displaying in Voyager Story after initial creation

### Tested on
Articulated Woolly Mammoth model on si-3ddigip01 test environment

### Actions to reproduce:
Add image to Media pane in UI
Drag image into Article Editor
Image shows up

<img width="1672" alt="Screen Shot 2019-12-06 at 12 04 02 PM" src="https://user-images.githubusercontent.com/49207360/70341291-a2594180-1820-11ea-8313-20f060cf0b74.png">

Save Article
Reopen article in Article Editor
A broken image icon shows up instead of the image

![image](https://user-images.githubusercontent.com/49207360/70341549-2f9c9600-1821-11ea-9ba3-4727a70955b5.png)

**Comment by framefactory** [comment] 2019-12-08 13:47
This issue is caused by the same limitation as issue #3. Closing this as a duplicate.

**Closed as completed by framefactory** 2019-12-08 13:47 UTC
