### ISSUE TITLE
Articles not loading in Voyager Explorer

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-concierge#3] opened 2019-12-06 16:50 UTC
### Issue:
Articles not displaying in Voyager Explorer

### Actions to reproduce:
On test environment go-to:
`/apps/voyager/voyager-explorer-dev.html?root=/view/7a042191-cd83-459b-bb5b-10d55d8b1f7a/&document=scene.svx.json`
Use 'eye icon' to open a scene in Voyager Explorer
Open Article Reader
Select article

Article reader displays the following message
`Article not found at articles/boogie-woogie.html`

![image](https://user-images.githubusercontent.com/49207360/70340190-4c839a00-181e-11ea-96db-74696a8b1a66.png)

**Comment by framefactory** [comment] 2019-12-08 13:44
This and issue #4 are caused by the fact that it's currently not possible to add additional files to a Concierge bin. Concierge currently is designed for migration only. We will add a workaround with the next release which allows creating new articles and uploading media files from within Voyager Story.

**Comment by framefactory** [comment] 2019-12-13 14:28
Fixed in master and ready for testing.

**Comment by framefactory** [comment] 2019-12-17 09:28
The fix has been included in the latest [release, v0.5.1](https://github.com/Smithsonian/dpo-concierge/releases/tag/v0.5.1)

**Closed as completed by framefactory** 2019-12-17 09:28 UTC
